# Generated by Django 5.1.6 on 2025-03-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=50),
        ),
    ]
